
title: Will's Programming Blog
email: willnewton10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  writing about programming
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: willnewton10
github_username:  willnewton10

# Build settings
markdown: kramdown
